name: CI

on: [push]

env:
  GO_VERSION: "1.17"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Module and build cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-pkg-mod-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}

      - name: Build
        run: make
